### ISSUE TITLE
Implement Desktop Support

### ISSUE THREAD

**Issue by mdrokz** [mdrokz/ani_mobile#10]
# TODO

- [ ] Implement FFI library in rust for libvlc
- [ ] Create flutter plugin for linux & windows that interfaces with the FFI library
- [ ] Implement the flutter plugin in `vlc_flutter_player`
